### ISSUE TITLE
Unable to access /api/private

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-laravel-api-samples#10]
Everytime I try to use postman to make an API call: 

curl --request GET \
  --url http://localhost:8000/api/private \
  --header 'authorization: Bearer <ACCESS TOKEN>'

I get "Sorry, the page you are looking for could not be found."

AUTH-3389

**Comment by aaguiarz** [comment]
Try setting the Accept header:

 curl  (...) -H 'Accept: application/json'

**Comment by Matschick** [comment]
I got the same problem. After I added accept header I get:

`"error": "Unauthenticated."` 

I send the Header authorization: Bearer mytoken.

**Comment by ioncode** [comment]
Same error, all done by https://auth0.com/docs/quickstart/backend/laravel

header succesfully passed to laravel, i can see him in $request->header(), but i can't access auth0 class to get info & route can not authorize
