### ISSUE TITLE
Getting user email in custom repository

### ISSUE THREAD

**Issue by lioneaglesolutions** [auth0-samples/auth0-laravel-api-samples#80]
This example shows that you can retrieve the email from the user attributes https://github.com/auth0-samples/auth0-laravel-api-samples/blob/master/app/app/Auth/CustomUserRepository.php#L29

However, both `email` and `name` are undefined array keys - how are you able to get the name and the email from the token when trying to map this to a user in your database in Laravel?

When dumping the user from the method `fromAccessToken`, the following is the output;

```
 [
  "iss" => "https://my-domain.au.auth0.com/"
  "sub" => "sub"
  "aud" => [ ... ]
  "iat" => 1668056990
  "exp" => 1668057110
  "azp" => "azp"
  "scope" => "openid profile email"
]
```

I know I can add a custom claim but then I have to include a URL - how can I get the email?

**Comment by evansims** [comment]
Hi @lioneaglesolutions 👋 This sample demonstrates Access Tokens, which don't include identity information, such as emails. [You can learn more about the differences between Access and ID Tokens here.](https://auth0.com/blog/id-token-access-token-what-is-the-difference/)

You'd need to [create a rule](https://manage.auth0.com/#/rules) to add the additional data you're seeking to your Access Tokens. From your Dashboard, go into Auth Pipeline > Rules, and choose 'Create'. This takes you to a gallery of templates you can base a new rule from. Under the Access Control, you'll find a rule called “add email to access token.” That should get you started with what you're looking for.

For additional guidance, the [Auth0 Community](https://community.auth0.com) has a great deal of conversations and resources to help on this.
